### ISSUE TITLE
Add schema validation before instantiating Route objects

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-routing#17]
The function [`dataToRoute(data)`](https://github.com/interledgerjs/ilp-routing/blob/master/src/lib/route.js#L133) expects the parameter `data` to comply to the route schema and, hence, this function should perform schema validation.

Currently, the connector [validates new routes against the schema](https://github.com/interledgerjs/ilp-connector/blob/master/src/lib/message-router.js#L109) before passing it on to `ilp-routing`. However, `ilp-core` also uses `ilp-routing` and it does not explicitly check that the routes comply to the schema.

**Comment by michielbdejong** [comment]
I think that function is no longer used, LiquidityCurve#setData now takes 3 data encodings, one of which is the binary/base64 curve format from the Route schema.
