### ISSUE TITLE
Combined Liquidity Curve

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-routing#19]
[Combining](https://github.com/interledgerjs/ilp-routing/blob/master/src/lib/liquidity-curve.js#L58) liquidity curves seems to be buggy.

For example, when setting up three ledgers L<sub>1</sub> (USD), L<sub>2</sub> (EUR), and L<sub>3</sub> (JYP) that are connected by two connectors C<sub>1</sub> and C<sub>2</sub> such that L<sub>1</sub> <-> C<sub>1</sub>  <-> L<sub>2</sub> <-> C<sub>2</sub> <-> L<sub>3</sub>, the public routing tables of the connectors look as following:

C<sub>1</sub> routing table
```
{
    "source_ledger": "demo.ledger1.",
    "destination_ledger": "demo.ledger2.",
    "points": [
        [0, -0.01],
        [100000000, 94062205.45654099]
    ],
    "min_message_window": 1,
    "source_account": "demo.ledger1.connie"
}, {
    "source_ledger": "demo.ledger1.",
    "destination_ledger": "demo.ledger3.",
    "points": [
        [0, 0],
        [0.010631262525050101, -0.01]
    ],
    "min_message_window": 2,
    "source_account": "demo.ledger1.connie"
}, {
    "source_ledger": "demo.ledger2.",
    "destination_ledger": "demo.ledger1.",
    "points": [
        [0, -0.01],
        [100000000, 105887799.99]
    ],
    "min_message_window": 1,
    "source_account": "demo.ledger2.connie"
}
```

C<sub>2</sub> routing table
```
{
    "source_ledger": "demo.ledger2.",
    "destination_ledger": "demo.ledger3.",
    "points": [
        [0, -0.01],
        [100000000, 12202545999.99]
    ],
    "min_message_window": 1,
    "source_account": "demo.ledger2.malory"
}, {
    "source_ledger": "demo.ledger3.",
    "destination_ledger": "demo.ledger1.",
    "points": [
        [0, 0],
        [1.2251503006012023, -0.01]
    ],
    "min_message_window": 2,
    "source_account": "demo.ledger3.malory"
}, {
    "source_ledger": "demo.ledger3.",
    "destination_ledger": "demo.ledger2.",
    "points": [
        [0, -0.01],
        [100000000, 816226.3742316186]
    ],
    "min_message_window": 1,
    "source_account": "demo.ledger3.malory"
}
```

The combined curve in C1's routing table consists of the points `[0, 0], [0.010631262525050101, -0.01]`. In consequence, the liquidity curve is only defined for payments with very small source amounts in the interval [0, 0.0106...]. Also, the y-coordinate of the second point is negative, which should not happen.

C2's combined curve has the same problem.

**Comment by sentientwaffle** [comment]
The negative y-coordinate is explained in https://github.com/interledgerjs/ilp-connector/blob/master/src/lib/routing-tables.js#L4-L31.

Re: small x coordinates: where are you getting those tables from?

**Comment by dappelt** [comment]
I assume that negative y-coordinates happen because of shifting the curve (i.e. rounding), correct? Is there any defined behavior for y-coordinate lesser than zero? Should we cap y-coords at zero?

How I get the tables: I print the public routing tables after a [new route is added](https://github.com/interledgerjs/ilp-connector/blob/master/src/lib/routing-tables.js#L67) with `toJSON`.

**Comment by sentientwaffle** [comment]
Yes, its due to shifting/rounding. We could cap it at 0.

If I run the following (where `route1_2` is `C1[0]` and `route2_1` is `C2[0]` from your example):
```
console.log(route1_2.join(route2_3).toJSON(10))
```

I get 
```
{ source_ledger: 'demo.ledger1.',
  destination_ledger: 'demo.ledger3.',
  points:
   [ [ 0, 0 ],
     [ 0.010631262525050101, -0.01 ],
     [ 100000000, 11477983889.438923 ] ],
  min_message_window: 2,
  source_account: 'demo.ledger1.connie' }
```
which has a third point not in your example, so I'm not sure whats going on.

**Comment by dappelt** [comment]
Nevermind, I called `toJSON()` without parameter for `maxPoints`. After changing it to `toJSON(10)` it gives me the same result that you got.

Interesting that when calling [`simplify`](https://github.com/interledgerjs/ilp-routing/blob/master/src/lib/liquidity-curve.js#L55) without parameter `maxPoints`, apparently the library we use does not set plausible default values. Removing the third point from the curve has a much bigger impact on the curve than removing the second point. Maybe we should check somewhere that `maxPoints` is a positive integer and if not set it to the constant we use for `maxPoints`.
